name: Build and push latest Rybbit Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "13 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: rybbit-io/rybbit

      - name: fix api
        run: sed -i "s@\"/add-site\"@\"/api/add-site\"@g" server/src/index.ts

      - name: Get current date and time
        id: datetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Get tag
      #  id: tag
      #  uses: devops-actions/action-get-tag@v1.0.1
      #  with:
      #    strip_v: true # Optional: Remove 'v' character from version

      - name: server Docker meta
        id: server-meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.actor }}/rybbit-server
          tags: |
            type=raw,value=${{ steps.datetime.outputs.datetime }}
            type=sha
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=true

      - name: Build and push server Docker images to ghcr.io
        uses: docker/build-push-action@v5
        with:
          build-args: |
            ANKI_VERSION=${{ needs.get-latest-tag.outputs.tag }}
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ steps.server-meta.outputs.tags }}
          labels: ${{ steps.server-meta.outputs.labels }}

      - name: client Docker meta
        id: client-meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.actor }}/rybbit-client
          tags: |
            type=raw,value=${{ steps.datetime.outputs.datetime }}
            type=sha
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=true

      - name: Build and push client Docker images to ghcr.io
        uses: docker/build-push-action@v5
        with:
          build-args: |
            ANKI_VERSION=${{ needs.get-latest-tag.outputs.tag }}
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ steps.client-meta.outputs.tags }}
          labels: ${{ steps.client-meta.outputs.labels }}
